# curl -X POST --location "http://127.0.0.1:8000/users"
POST http://127.0.0.1:8000/users
Content-Type: application/json
Cookie: first_name=first-value

{ "first_name": "Brian", "last_name":  "O'Kelly", "email": "brianjrok@gmail.com", "roles": ["user"]}

###

# curl -X PUT --location "http://127.0.0.1:8000/users/37aeb7bf-087c-4776-bc8d-0d8ced73b0af"
PUT http://127.0.0.1:8000/users/37aeb7bf-087c-4776-bc8d-0d8ced73b0af
Content-Type: application/json
Cookie: first_name=first-value

{ "first_name": "New", "last_name":  "Name", "middle_name": "Jozef", "email": "brianjrok@gmail.com", "roles": ["user"]}
###

